# Generated by Django 3.2.5 on 2021-08-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Applicant', 'Applicant'), ('Faculty', 'Faculty'), ('Alumnus', 'Alumnus')], default='---', max_length=20, verbose_name='category')),
                ('password', models.CharField(default='', max_length=15)),
                ('phonenum', models.DecimalField(decimal_places=0, default='', max_digits=11, verbose_name='phone Number')),
                ('idnum', models.IntegerField(verbose_name='id Number')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(default='', verbose_name='purpose')),
                ('date', models.DateField(default='')),
                ('dept', models.CharField(choices=[('reg', 'Register'), ('OAA', 'Office of Academic Affairs'), ('OSA', 'Faculty'), ('faculty', 'Faculties')], default='', max_length=10, verbose_name='department')),
                ('status', models.TextField(choices=[('Accept', 'Accept'), ('Deny', 'Deny'), ('Pending', 'Pending')], default='pending', max_length=20, null=True, verbose_name='status')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TUPConline_appointment.visit')),
            ],
        ),
    ]
