# Generated by Django 3.2.5 on 2021-08-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPConline_appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dept',
            field=models.CharField(choices=[('reg', 'Register'), ('OAA', 'Office of Academic Affairs'), ('OSA', 'Office of Student Affairs'), ('Campus Director', 'Campus Director'), ('Uitc', 'University Information Technology Center'), ('Finance', 'Finance'), ('Procurement', 'Procurement'), ('Research and Extension', 'Research and Extension'), ('PE ', 'Physical Education Faculty'), ('ie ', 'Industrial Education Faculty'), ('ms ', 'Math and Science Faculty'), ('IT ', 'Industrial Technology Faculty'), ('eng ', 'Engineering Faculty'), ('liberal', 'Liberal Arts Faculty'), ('lib ', 'Libary')], default='', max_length=50, verbose_name='department'),
        ),
    ]
