# Generated by Django 3.2.5 on 2021-08-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUPConline_appointment', '0002_alter_schedule_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='visitor',
            new_name='fullname',
        ),
    ]
