# Generated by Django 3.2.5 on 2021-08-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUPConline_appointment', '0003_rename_visitor_schedule_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fullname',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TUPConline_appointment.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='fullname',
            field=models.CharField(default='', max_length=50, verbose_name='fullname'),
        ),
    ]
