# Generated by Django 3.2.5 on 2021-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPConline_appointment', '0004_auto_20210820_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Applicant', 'Applicant'), ('Faculty', 'Faculty'), ('Alumnus', 'Alumnus')], default='---', max_length=20, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fullname',
            field=models.CharField(default='', max_length=50, verbose_name='fullname'),
        ),
        migrations.DeleteModel(
            name='visit',
        ),
    ]
