# Generated by Django 3.2.5 on 2021-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPConline_appointment', '0005_auto_20210823_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('password', models.TextField(default='', max_length=10)),
            ],
        ),
    ]
