# Generated by Django 3.2.5 on 2021-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPConline_appointment', '0008_alter_schedule_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Applicant', 'Applicant'), ('Faculty Member', 'Faculty Member'), ('Staff', 'Staff'), ('Alumnus', 'Alumnus')], default='---', max_length=20, verbose_name='category'),
        ),
    ]
